# Generated by Django 2.0.7 on 2018-09-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tradingjournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=50)),
                ('trade_date', models.DateTimeField()),
                ('action', models.CharField(max_length=20)),
                ('allocation', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('pub_date', models.DateTimeField()),
                ('justification', models.TextField()),
                ('tags', models.CharField(max_length=300)),
            ],
        ),
    ]
