# Generated by Django 2.0.7 on 2018-11-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradejournal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingjournal',
            name='prev_allocation',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
