# Generated by Django 2.0.7 on 2018-07-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='company',
            field=models.CharField(max_length=50),
        ),
    ]
